version: 2

project_name: drawx

builds:
  - skip: true

source:
  enabled: false

checksum:
  name_template: "drawx_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  use: github

release:
  prerelease: auto
  make_latest: true
  mode: keep-existing
  extra_files:
    - glob: ./dist-bundles/**/*.deb
    - glob: ./dist-bundles/**/*.rpm
    - glob: ./dist-bundles/**/*.AppImage
    - glob: ./dist-bundles/**/*.msi
    - glob: ./dist-bundles/**/*.exe
    - glob: ./dist-bundles/**/*.dmg
    - glob: ./dist-bundles/**/*.app.tar.gz
    - glob: ./dist-bundles/**/*.AppImage.tar.gz
    - glob: ./dist-bundles/**/*.nsis.zip
    - glob: ./dist-bundles/**/*.sig
