[tools]
deno = "latest"
rust = "latest"
cargo-make = "latest"
rust-analyzer = "latest"
node = "22"
biome = "latest"
nub = "latest"
ghalint = "latest"
act = "latest"
cargo-binstall = "latest"
minisign = "latest"

[tasks]
install = { run = "nub install" }
update = { run = "nub update" }
build = { run = "nub run tauri build" }
lint = { run = "nub run lint ." }
format = { run = "nub run format ." }
