// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the service bound to the frontend. Its exported methods are
 * callable from TypeScript through the generated bindings in
 * frontend/bindings/drawx.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListCanvases returns all canvases ordered by most recently updated.
 */
export function ListCanvases(): $CancellablePromise<$models.Canvas[]> {
    return $Call.ByName("drawx.AppService.ListCanvases");
}

/**
 * CreateCanvas inserts a new empty canvas and returns it.
 */
export function CreateCanvas(title: string): $CancellablePromise<$models.Canvas> {
    return $Call.ByName("drawx.AppService.CreateCanvas", title);
}

/**
 * DeleteCanvas removes a canvas by id.
 */
export function DeleteCanvas(id: string): $CancellablePromise<void> {
    return $Call.ByName("drawx.AppService.DeleteCanvas", id);
}

/**
 * LoadCanvas returns the canvas with the given id, or null when it does not
 * exist.
 */
export function LoadCanvas(id: string): $CancellablePromise<$models.Canvas | null> {
    return $Call.ByName("drawx.AppService.LoadCanvas", id);
}

/**
 * SaveCanvas replaces the elements, app state and files of a canvas.
 */
export function SaveCanvas(id: string, elements: any[], appState: any, files: any): $CancellablePromise<void> {
    return $Call.ByName("drawx.AppService.SaveCanvas", id, elements, appState, files);
}

/**
 * UpdateCanvasTitle renames a canvas.
 */
export function UpdateCanvasTitle(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByName("drawx.AppService.UpdateCanvasTitle", id, title);
}

/**
 * ListLibraries returns all stored libraries ordered by name.
 */
export function ListLibraries(): $CancellablePromise<$models.Library[]> {
    return $Call.ByName("drawx.AppService.ListLibraries");
}

/**
 * SaveLibraries upserts a batch of libraries.
 */
export function SaveLibraries(libraries: $models.Library[]): $CancellablePromise<void> {
    return $Call.ByName("drawx.AppService.SaveLibraries", libraries);
}

/**
 * ClearLibraries removes all stored libraries.
 */
export function ClearLibraries(): $CancellablePromise<void> {
    return $Call.ByName("drawx.AppService.ClearLibraries");
}

/**
 * GetDbPath returns the absolute path of the SQLite database file.
 */
export function GetDbPath(): $CancellablePromise<string> {
    return $Call.ByName("drawx.AppService.GetDbPath");
}
