// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Canvas is a single drawing document.
 */
export interface Canvas {
    id: string;
    title: string;
    description?: string | null;
    createdAt: string;
    updatedAt: string;
    elements: any[];
    appState: any;
    files: any;
}

/**
 * Author of a community library.
 */
export interface Author {
    name: string;
    url?: string;
}

/**
 * Library is a community library stored in the database.
 */
export interface Library {
    id: string;
    name: string;
    description: string;
    authors: Author[];
    source: string;
    preview: string;
    created: string;
    updated: string;
    version: number;
    itemNames?: string[] | null;
    content?: any;
}
