name: Tauri PR Check

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jdx/mise:2026.8.16
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@main
      - name: check
        run: |
            mise deps
            mise install
            mise run tauri:build
