name: Tauri PR Check

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
      
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@main

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libssl-dev \
            libxdo-dev \
            patchelf \
            file \
            squashfs-tools

      - name: Install dependencies
        run: |
          rm -f package-lock.json
          bun install
          bun run tauri build
